spring:
  application:
    name: bookingms
  config:
    import: file:env.properties
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: bookingms
      connection-init-sql: SELECT 1
      auto-commit: true
      connection-timeout: 30000
      max-lifetime: 2000000
      idle-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
